import type { HeroEnum } from '../select-hero/types'
import type { Building } from './types'

export const BUILDINGS_ELF: Building[] = [
	{
		id: 'elf_11',
		name: 'Горн',
		description: '+1 к итоговой силе войск в сражении.',
		level: 1,
		price: { coin: 1, iron: 3, wood: 0 },
		dependencies: [],
	},
	{
		id: 'elf_12',
		name: 'Заросли пикси',
		description: 'Наём пикси.',
		level: 1,
		price: { coin: 0, iron: 2, wood: 2 },
		dependencies: [],
	},
	{
		id: 'elf_21',
		name: 'Лавка бронника',
		description:
			'Заплатите X Дерева перед сражением, чтобы модифицировать X юнитов в этом сражении.',
		level: 2,
		price: { coin: 0, iron: 4, wood: 0 },
		dependencies: ['elf_11'],
	},
	{
		id: 'elf_22',
		name: 'Гнездовье',
		description:
			'Наём грифонов. Можете забирать Артефакты за Дерево, если грифонов в вашем войске ≥ цене этого Артефакта в Дереве.',
		level: 2,
		price: { coin: 0, iron: 3, wood: 3 },
		dependencies: ['elf_12'],
	},
	{
		id: 'elf_31',
		name: 'Лесистый утёс',
		description: 'Вы не тратите дерево при строительстве.',
		level: 3,
		price: { coin: 0, iron: 6, wood: 0 },
		dependencies: ['elf_11'],
	},
	{
		id: 'elf_32',
		name: 'Обсерватория',
		description: 'При перемещении получайте +1 подкову.',
		level: 3,
		price: { coin: 0, iron: 2, wood: 3 },
		dependencies: ['elf_21', 'elf_22'],
	},
	{
		id: 'elf_33',
		name: 'Дозор',
		description: '+2 ПО в конце игры за каждую захваченную крепость.',
		level: 3,
		price: { coin: 2, iron: 2, wood: 2 },
		dependencies: ['elf_22'],
	},
	{
		id: 'elf_41',
		name: 'Путеводный лес',
		description: 'Стоимость перемещения по лесу становится = 1.',
		level: 4,
		price: { coin: 2, iron: 4, wood: 0 },
		dependencies: ['elf_31'],
	},
	{
		id: 'elf_42',
		name: 'Дом друида',
		description: '+1 ПО в конце игры за каждый свой артефакт.',
		level: 4,
		price: { coin: 2, iron: 5, wood: 2 },
		dependencies: ['elf_32'],
	},
	{
		id: 'elf_43',
		name: 'Великое древо',
		description: 'Наём энтов.',
		level: 4,
		price: { coin: 3, iron: 5, wood: 3 },
		dependencies: ['elf_32', 'elf_33'],
	},
]

const BUILDINGS_GNOME: Building[] = [
	{
		id: 'gnome_11',
		name: 'Генератор',
		description:
			'Получить 1 * за каждого механикаа в войске на момент строительства.',
		level: 1,
		price: { coin: 2, iron: 3, wood: 0 },
		dependencies: [],
	},
	{
		id: 'gnome_12',
		name: 'Академия',
		description:
			'Наём механиков. Каждый механик в сражении удваивает силу 1 любой боевой единицы.',
		level: 1,
		price: { coin: 0, iron: 2, wood: 2 },
		dependencies: [],
	},
	{
		id: 'gnome_21',
		name: 'Сборщики',
		description: 'Получите 1 * и 9 любых ресурсов.',
		level: 2,
		price: { coin: 0, iron: 5, wood: 0 },
		dependencies: [],
	},
	{
		id: 'gnome_22',
		name: 'Библиотека',
		description: '',
		level: 2,
		price: { coin: 0, iron: 2, wood: 3 },
		dependencies: [],
	},
	{
		id: 'gnome_23',
		name: 'Мануфактура',
		description: '',
		level: 2,
		price: { coin: 2, iron: 3, wood: 0 },
		dependencies: ['gnome_12'],
	},
	{
		id: 'gnome_31',
		name: 'Лаборатория',
		description: '',
		level: 3,
		price: { coin: 2, iron: 4, wood: 0 },
		dependencies: ['gnome_21'],
	},
	{
		id: 'gnome_32',
		name: 'Конвейер',
		description: '',
		level: 3,
		price: { coin: 0, iron: 5, wood: 2 },
		dependencies: ['gnome_22'],
	},
	{
		id: 'gnome_33',
		name: 'Цех',
		description: '',
		level: 3,
		price: { coin: 0, iron: 5, wood: 0 },
		dependencies: ['gnome_23'],
	},
	{
		id: 'gnome_41',
		name: 'Банк',
		description: '',
		level: 4,
		price: { coin: 2, iron: 5, wood: 2 },
		dependencies: ['gnome_32'],
	},
	{
		id: 'gnome_42',
		name: 'Фабрика',
		description: '',
		level: 4,
		price: { coin: 2, iron: 5, wood: 2 },
		dependencies: ['gnome_32'],
	},
]

const BUILDINGS_ORC: Building[] = [
	{
		id: 'orc_11',
		name: 'Идол войны',
		description: '',
		level: 1,
		price: { coin: 2, iron: 2, wood: 0 },
		dependencies: [],
	},
	{
		id: 'orc_21',
		name: 'Свалка',
		description: '',
		level: 2,
		price: { coin: 2, iron: 4, wood: 2 },
		dependencies: ['orc_11'],
	},
	{
		id: 'orc_22',
		name: 'Арена',
		description: '',
		level: 2,
		price: { coin: 3, iron: 3, wood: 3 },
		dependencies: [],
	},
	{
		id: 'orc_23',
		name: 'Лагерь',
		description: '',
		level: 2,
		price: { coin: 0, iron: 2, wood: 2 },
		dependencies: [],
	},
	{
		id: 'orc_31',
		name: 'Дом вождей',
		description: '',
		level: 3,
		price: { coin: 0, iron: 4, wood: 0, rage: 3 },
		dependencies: ['orc_21', 'orc_22'],
	},
	{
		id: 'orc_32',
		name: 'Загон',
		description: '',
		level: 3,
		price: { coin: 0, iron: 4, wood: 4, rage: 2 },
		dependencies: ['orc_22'],
	},
	{
		id: 'orc_33',
		name: 'Качалка',
		description: '',
		level: 3,
		price: { coin: 3, iron: 5, wood: 0 },
		dependencies: ['orc_23'],
	},
	{
		id: 'orc_41',
		name: 'Трофейная',
		description: '',
		level: 4,
		price: { coin: 0, iron: 6, wood: 0, rage: 2 },
		dependencies: ['orc_31'],
	},
	{
		id: 'orc_42',
		name: 'Металка',
		description: '',
		level: 4,
		price: { coin: 3, iron: 3, wood: 3, rage: 3 },
		dependencies: ['orc_32'],
	},
	{
		id: 'orc_43',
		name: 'Великое древо',
		description: 'Наём энтов.',
		level: 4,
		price: { coin: 0, iron: 4, wood: 4, rage: 4 },
		dependencies: ['orc_32', 'orc_33'],
	},
]

const BUILDINGS_UNDEAD: Building[] = [
	{
		id: 'undead_11',
		name: 'Курган',
		description: '',
		level: 1,
		price: { coin: 0, iron: 4, wood: 0 },
		dependencies: [],
	},
	{
		id: 'undead_12',
		name: 'Катафалк',
		description: '',
		level: 1,
		price: { coin: 2, iron: 2, wood: 2 },
		dependencies: [],
	},
	{
		id: 'undead_13',
		name: 'Кладбище',
		description: '',
		level: 1,
		price: { coin: 1, iron: 0, wood: 3 },
		dependencies: [],
	},
	{
		id: 'undead_21',
		name: 'Склеп',
		description: '',
		level: 2,
		price: { coin: 0, iron: 5, wood: 0 },
		dependencies: ['undead_11'],
	},
	{
		id: 'undead_22',
		name: 'Алтарь',
		description: '',
		level: 2,
		price: { coin: 0, iron: 4, wood: 0 },
		dependencies: ['undead_11', 'undead_12', 'undead_13'],
	},
	{
		id: 'undead_23',
		name: 'Руины замка',
		description: '',
		level: 2,
		price: { coin: 0, iron: 4, wood: 4 },
		dependencies: ['undead_13'],
	},
	{
		id: 'undead_31',
		name: 'Часовня',
		description: '',
		level: 3,
		price: { coin: 4, iron: 5, wood: 0 },
		dependencies: ['undead_22'],
	},
	{
		id: 'undead_32',
		name: 'Чумной столб',
		description: '',
		level: 3,
		price: { coin: 0, iron: 5, wood: 0 },
		dependencies: ['undead_23'],
	},
	{
		id: 'undead_41',
		name: 'Капище',
		description: '',
		level: 4,
		price: { coin: 0, iron: 0, wood: 5 },
		dependencies: ['undead_31'],
	},
	{
		id: 'undead_42',
		name: 'Костница',
		description: '',
		level: 4,
		price: { coin: 0, iron: 6, wood: 4 },
		dependencies: ['undead_32'],
	},
]

const BUILDINGS_NAGA: Building[] = [
	{
		id: 'naga_11',
		name: 'Кормушка',
		description: '',
		level: 1,
		price: { coin: 0, iron: 0, wood: 0, crac: 3 },
		dependencies: [],
	},
	{
		id: 'naga_12',
		name: 'Дворец',
		description: '',
		level: 1,
		price: { coin: 0, iron: 0, wood: 0, crac: 4 },
		dependencies: [],
	},
	{
		id: 'naga_13',
		name: 'Риф',
		description: '',
		level: 1,
		price: { coin: 0, iron: 0, wood: 0, crac: 3 },
		dependencies: [],
	},
	{
		id: 'naga_21',
		name: 'Шахта',
		description: '',
		level: 2,
		price: { coin: 0, iron: 0, wood: 0, crac: 2 },
		dependencies: [],
	},
	{
		id: 'naga_22',
		name: 'Гейзер',
		description: '',
		level: 2,
		price: { coin: 0, iron: 0, wood: 0, crac: 2 },
		dependencies: [],
	},
	{
		id: 'naga_23',
		name: 'Корабль',
		description: '',
		level: 2,
		price: { coin: 0, iron: 0, wood: 0, crac: 2 },
		dependencies: [],
	},
	{
		id: 'naga_31',
		name: 'Храм',
		description: '',
		level: 3,
		price: { coin: 0, iron: 0, wood: 0, crac: 4 },
		dependencies: [],
	},
	{
		id: 'naga_32',
		name: 'Плотина',
		description: '',
		level: 3,
		price: { coin: 0, iron: 0, wood: 0, crac: 3 },
		dependencies: [],
	},
	{
		id: 'naga_41',
		name: 'Маяк',
		description: '',
		level: 4,
		price: { coin: 0, iron: 0, wood: 0, crac: 3 },
		dependencies: [],
	},
	{
		id: 'naga_42',
		name: 'Сердце океана',
		description: '',
		level: 4,
		price: { coin: 0, iron: 0, wood: 0, crac: 3 },
		dependencies: [],
	},
]

const BUILDINGS_HUMAN: Building[] = [
	{
		id: 'human_11',
		name: 'Ратуша',
		description: '',
		level: 1,
		price: { coin: 2, iron: 2, wood: 2 },
		dependencies: [],
	},
	{
		id: 'human_12',
		name: 'Гильдия войнов',
		description: '',
		level: 1,
		price: { coin: 0, iron: 4, wood: 0 },
		dependencies: [],
	},
	{
		id: 'human_21',
		name: 'Рынок',
		description: '',
		level: 2,
		price: { coin: 0, iron: 4, wood: 0 },
		dependencies: [],
	},
	{
		id: 'human_22',
		name: 'Башня иллюзий',
		description: '',
		level: 2,
		price: { coin: 0, iron: 3, wood: 0 },
		dependencies: ['human_11'],
	},
	{
		id: 'human_31',
		name: 'Дом следопытов',
		description: '',
		level: 3,
		price: { coin: 0, iron: 2, wood: 3 },
		dependencies: ['human_21'],
	},
	{
		id: 'human_32',
		name: 'Таверна',
		description: '',
		level: 3,
		price: { coin: 0, iron: 4, wood: 3 },
		dependencies: ['human_22'],
	},
	{
		id: 'human_33',
		name: 'Казармы',
		description: '',
		level: 3,
		price: { coin: 0, iron: 4, wood: 0 },
		dependencies: ['human_22', 'human_12'],
	},
	{
		id: 'human_41',
		name: 'Арсенал',
		description: '',
		level: 4,
		price: { coin: 5, iron: 3, wood: 3 },
		dependencies: ['human_31'],
	},
	{
		id: 'human_42',
		name: 'Собор',
		description: '',
		level: 4,
		price: { coin: 0, iron: 5, wood: 0 },
		dependencies: ['human_32'],
	},
	{
		id: 'human_43',
		name: 'Гильдия магов',
		description: '',
		level: 4,
		price: { coin: 3, iron: 5, wood: 3 },
		dependencies: ['human_33'],
	},
]

const BUILDINGS_CULTIST: Building[] = [
	{
		id: 'cultist_11',
		name: 'Дары владыки',
		description: '',
		level: 1,
		price: { coin: 1, iron: 2, wood: 1 },
		dependencies: [],
	},
	{
		id: 'cultist_12',
		name: 'Дыхание владыки',
		description: '',
		level: 1,
		price: { coin: 3, iron: 3, wood: 0 },
		dependencies: [],
	},
	{
		id: 'cultist_21',
		name: 'Символ веры',
		description: '',
		level: 2,
		price: { coin: 3, iron: 2, wood: 1 },
		dependencies: ['cultist_11'],
	},
	{
		id: 'cultist_22',
		name: 'Око владыки',
		description: '',
		level: 2,
		price: { coin: 2, iron: 2, wood: 2 },
		dependencies: [],
	},
	{
		id: 'cultist_31',
		name: 'Святилище',
		description: '',
		level: 3,
		price: { coin: 1, iron: 3, wood: 2 },
		dependencies: [],
	},
	{
		id: 'cultist_32',
		name: 'Храм владыки',
		description: '',
		level: 3,
		price: { coin: 0, iron: 4, wood: 2 },
		dependencies: ['cultist_22'],
	},
	{
		id: 'cultist_33',
		name: 'Алтарь',
		description: '',
		level: 3,
		price: { coin: 2, iron: 4, wood: 0 },
		dependencies: [],
	},
	{
		id: 'cultist_41',
		name: 'Пришествие',
		description: '',
		level: 4,
		price: { coin: 2, iron: 4, wood: 4 },
		dependencies: ['cultist_31', 'cultist_32'],
	},
	{
		id: 'cultist_42',
		name: 'Посвящение',
		description: '',
		level: 4,
		price: { coin: 2, iron: 3, wood: 3 },
		dependencies: ['cultist_33'],
	},
]

const BUILDINGS_GREMLIN: Building[] = [
	{
		id: 'gremlin_11',
		name: 'Базар',
		description: '',
		level: 1,
		price: { coin: 2, iron: 2, wood: 2 },
		dependencies: [],
	},
	{
		id: 'gremlin_12',
		name: 'Бизнес-план',
		description: '',
		level: 1,
		price: { coin: 2, iron: 2, wood: 0 },
		dependencies: [],
	},
	{
		id: 'gremlin_13',
		name: 'Трущобы',
		description: '',
		level: 1,
		price: { coin: 0, iron: 4, wood: 0 },
		dependencies: [],
	},
	{
		id: 'gremlin_21',
		name: 'Барахолка',
		description: '',
		level: 2,
		price: { coin: 0, iron: 3, wood: 2 },
		dependencies: ['gremlin_11'],
	},
	{
		id: 'gremlin_22',
		name: 'Взрывные бочки',
		description: '',
		level: 2,
		price: { coin: 0, iron: 5, wood: 0 },
		dependencies: [],
	},
	{
		id: 'gremlin_23',
		name: 'Квасоварня',
		description: '',
		level: 2,
		price: { coin: 2, iron: 4, wood: 2 },
		dependencies: ['gremlin_12'],
	},
	{
		id: 'gremlin_31',
		name: 'Игровой клуб',
		description: '',
		level: 3,
		price: { coin: 0, iron: 5, wood: 0 },
		dependencies: ['gremlin_21'],
	},
	{
		id: 'gremlin_32',
		name: 'Ломбард',
		description: '',
		level: 3,
		price: { coin: 0, iron: 3, wood: 2 },
		dependencies: ['gremlin_21', 'gremlin_22'],
	},
	{
		id: 'gremlin_33',
		name: 'Драконодром',
		description: '',
		level: 3,
		price: { coin: 0, iron: 9, wood: 6 },
		dependencies: [],
	},
	{
		id: 'gremlin_41',
		name: 'Торговая палата',
		description: '',
		level: 4,
		price: { coin: 2, iron: 5, wood: 0 },
		dependencies: ['gremlin_32', 'gremlin_33'],
	},
]
const BUILDINGS_ROBOT: Building[] = [
	{
		id: 'robot_11',
		name: 'Локатор',
		description: '',
		level: 1,
		price: { coin: 3, iron: 0, wood: 2 },
		dependencies: [],
	},
	{
		id: 'robot_12',
		name: 'Капсула',
		description: '',
		level: 1,
		price: { coin: 1, iron: 0, wood: 3 },
		dependencies: [],
	},
	{
		id: 'robot_21',
		name: 'Технопарк',
		description: '',
		level: 2,
		price: { coin: 0, iron: 0, wood: 4 },
		dependencies: ['robot_11'],
	},
	{
		id: 'robot_22',
		name: 'Бункер',
		description: '',
		level: 2,
		price: { coin: 4, iron: 0, wood: 2 },
		dependencies: [],
	},
	{
		id: 'robot_31',
		name: 'Прокси-сервер',
		description: '',
		level: 3,
		price: { coin: 3, iron: 0, wood: 3 },
		dependencies: [],
	},
	{
		id: 'robot_32',
		name: 'Генераторы',
		description: '',
		level: 3,
		price: { coin: 5, iron: 0, wood: 7 },
		dependencies: ['robot_21', 'robot_22'],
	},
	{
		id: 'robot_41',
		name: 'Пневмопочта',
		description: '',
		level: 4,
		price: { coin: 3, iron: 0, wood: 6 },
		dependencies: ['robot_31'],
	},
	{
		id: 'robot_42',
		name: 'Ангар',
		description: '',
		level: 4,
		price: { coin: 0, iron: 0, wood: 7 },
		dependencies: ['robot_31', 'robot_32'],
	},
]

const BUILDINGS_ELEMENTAL: Building[] = [
	{
		id: 'elemental_11',
		name: 'Бездонная сумка',
		description: '',
		level: 1,
		price: { coin: 0, iron: 1, wood: 4 },
		dependencies: [],
	},
	{
		id: 'elemental_12',
		name: 'Пески времени',
		description: '',
		level: 1,
		price: { coin: 1, iron: 3, wood: 0 },
		dependencies: [],
	},
	{
		id: 'elemental_13',
		name: 'Парящие башни',
		description: '',
		level: 1,
		price: { coin: 0, iron: 4, wood: 2 },
		dependencies: ['elemental_12'],
	},
	{
		id: 'elemental_21',
		name: 'Ковёр-самолёт',
		description: '',
		level: 2,
		price: { coin: 0, iron: 4, wood: 0 },
		dependencies: ['elemental_11'],
	},
	{
		id: 'elemental_22',
		name: 'Путеводная нить',
		description: '',
		level: 2,
		price: { coin: 2, iron: 2, wood: 2 },
		dependencies: ['elemental_12'],
	},
	{
		id: 'elemental_23',
		name: 'Зелёные террасы',
		description: '',
		level: 2,
		price: { coin: 0, iron: 2, wood: 4 },
		dependencies: ['elemental_12'],
	},
	{
		id: 'elemental_31',
		name: 'Колпак-невидимка',
		description: '',
		level: 3,
		price: { coin: 0, iron: 7, wood: 0 },
		dependencies: ['elemental_21'],
	},
	{
		id: 'elemental_32',
		name: 'Кривое зеркало',
		description: '',
		level: 3,
		price: { coin: 0, iron: 4, wood: 4 },
		dependencies: ['elemental_21', 'elemental_22'],
	},
	{
		id: 'elemental_33',
		name: 'Жар-дворец',
		description: '',
		level: 3,
		price: { coin: 3, iron: 7, wood: 0 },
		dependencies: ['elemental_32'],
	},
	{
		id: 'elemental_41',
		name: 'Волшебная лампа',
		description: '',
		level: 4,
		price: { coin: 0, iron: 15, wood: 0 },
		dependencies: ['elemental_31', 'elemental_32'],
	},
	{
		id: 'elemental_42',
		name: 'Чертоги хрусталя',
		description: '',
		level: 4,
		price: { coin: 7, iron: 3, wood: 0 },
		dependencies: ['elemental_32'],
	},
]

const BUILDINGS_DEMON: Building[] = [
	{
		id: 'demon_11',
		name: 'Клеймо',
		description: '',
		level: 1,
		price: { coin: 2, iron: 0, wood: 2 },
		dependencies: [],
	},
	{
		id: 'demon_12',
		name: 'Чистилище',
		description: '',
		level: 1,
		price: { coin: 1, iron: 2, wood: 1 },
		dependencies: [],
	},
	{
		id: 'demon_13',
		name: 'Круг призыва',
		description: '',
		level: 1,
		price: { coin: 2, iron: 2, wood: 0 },
		dependencies: [],
	},
	{
		id: 'demon_21',
		name: 'Псарня',
		description: '',
		level: 2,
		price: { coin: 1, iron: 1, wood: 1 },
		dependencies: [],
	},
	{
		id: 'demon_22',
		name: 'Кости',
		description: '',
		level: 2,
		price: { coin: 2, iron: 2, wood: 1 },
		dependencies: ['demon_11', 'demon_12'],
	},
	{
		id: 'demon_23',
		name: 'Будуар',
		description: '',
		level: 2,
		price: { coin: 2, iron: 2, wood: 1 },
		dependencies: ['demon_13'],
	},
	{
		id: 'demon_31',
		name: 'Контракт',
		description: '',
		level: 3,
		price: { coin: 0, iron: 4, wood: 2 },
		dependencies: ['demon_21'],
	},
	{
		id: 'demon_32',
		name: 'Грехи',
		description: '',
		level: 3,
		price: { coin: 2, iron: 4, wood: 0 },
		dependencies: ['demon_21', 'demon_22'],
	},
	{
		id: 'demon_33',
		name: 'Адская кухня',
		description: '',
		level: 3,
		price: { coin: 0, iron: 5, wood: 6 },
		dependencies: ['demon_22'],
	},
	{
		id: 'demon_41',
		name: 'Карета',
		description: '',
		level: 4,
		price: { coin: 3, iron: 7, wood: 0 },
		dependencies: ['demon_31'],
	},
	{
		id: 'demon_42',
		name: 'Плоть',
		description: '',
		level: 4,
		price: { coin: 1, iron: 4, wood: 2 },
		dependencies: ['demon_32'],
	},
	{
		id: 'demon_43',
		name: 'Кладовая',
		description: '',
		level: 4,
		price: { coin: 0, iron: 9, wood: 0 },
		dependencies: ['demon_33'],
	},
]

const BUILDINGS_HALFGROWN: Building[] = [
	{
		id: 'halfgrown_11',
		name: 'Вербовка',
		description: '',
		level: 1,
		price: { coin: 2, iron: 0, wood: 5 },
		dependencies: [],
	},
	{
		id: 'halfgrown_12',
		name: 'Бани',
		description: '',
		level: 1,
		price: { coin: 0, iron: 5, wood: 2 },
		dependencies: [],
	},
	{
		id: 'halfgrown_13',
		name: 'Малая школа',
		description: '',
		level: 1,
		price: { coin: 5, iron: 2, wood: 0 },
		dependencies: [],
	},
	{
		id: 'halfgrown_21',
		name: 'Акведук',
		description: '',
		level: 2,
		price: { coin: 2, iron: 2, wood: 3 },
		dependencies: [],
	},
	{
		id: 'halfgrown_22',
		name: 'Колизей',
		description: '',
		level: 2,
		price: { coin: 2, iron: 3, wood: 2 },
		dependencies: [],
	},
	{
		id: 'halfgrown_23',
		name: 'Военный лагерь',
		description: '',
		level: 2,
		price: { coin: 3, iron: 2, wood: 2 },
		dependencies: [],
	},
]

export const HEROES_BUILDINGS: Record<HeroEnum, Building[]> = {
	robot: BUILDINGS_ROBOT,
	human: BUILDINGS_HUMAN,
	orc: BUILDINGS_ORC,
	elf: BUILDINGS_ELF,
	undead: BUILDINGS_UNDEAD,
	gnome: BUILDINGS_GNOME,
	naga: BUILDINGS_NAGA,
	cultist: BUILDINGS_CULTIST,
	elemental: BUILDINGS_ELEMENTAL,
	gremlin: BUILDINGS_GREMLIN,
	demon: BUILDINGS_DEMON,
	halfgrown: BUILDINGS_HALFGROWN,
}
